Project2/urls.py
#import imp
from django.urls import include, path
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('unit3/',include("blog.urls"),name="unit3"),
    path('unit2/',include("account.urls"),name="unit2"),
    path('',include("firstPage.urls")),
    
]

account/urls.py
from django.urls import path
from .views import generate_report,home_page_unit,get_report


urlpatterns = [
 
    path('report/',generate_report,name="unit2rep"),
    path('record/',get_report,name="unit2rec"),
    path('',home_page_unit,name='home2'),
 
]

blog/urls.py
#from django.conf.urls import include
#from django.conf.urls import repath as url
from django.urls import path
from django.conf.urls import include
from blog.views import generate_result, get_report, home_page
#from blog import views as myapp_views
#from .views import generate_result,get_report,home_page

urlpatterns = [
 
    path('report/',generate_result,name="rep"),
    path('record/',get_report,name="rec"),
    path('',home_page,name='home3'),
]

account/models.py
from django.db import models
from blog.models import PlagiarismReport
# Create your models here.

class PlagiarismRecordU_2(models.Model):
    report=models.ForeignKey(PlagiarismReport,on_delete=models.CASCADE)
    student_1=models.CharField(max_length=15)
    student_2=models.CharField(max_length=15)
    similarity_code=models.FloatField()
    similarity_ids=models.FloatField()
    similarity_classes=models.FloatField()
    similarity_content=models.FloatField()
    similarity_type=models.FloatField()
    similarity_value=models.FloatField()
    similatity_hrefs=models.FloatField()
    similarity_srcs=models.FloatField()
    similarity_others=models.FloatField()
    
    def __str__(self):
        return self.student_1+' '+self.student_2+' '+str(self.similarity_code)+' '+str(self.similarity_ids)+' '+str(self.similarity_classes)+' '+str(self.similarity_content)+' '+str(self.similarity_type)+' '+str(self.similarity_value)+' '+str(self.similatity_hrefs)+' '+str(self.similarity_srcs)+' '+str(self.similarity_others)

blog/models.py
from django.db import models

# Create your models here.
class PlagiarismReport(models.Model):
    #cohort, unit, sprint, file_name, extension)
    cohort_id=models.CharField(max_length=15)
    unit=models.IntegerField()
    sprint=models.IntegerField()
    filename=models.CharField(max_length=255)
    extension=models.CharField(max_length=10)
    token=models.CharField(max_length=100000)
    def __str__(self):
        return self.cohort_id+' '+str(self.unit)+'  '+str(self.sprint)+' '+' '+self.filename+' '+self.extension+' '+self.token


class PlagiarismRecordU_3(models.Model):
    report=models.ForeignKey(PlagiarismReport,on_delete=models.CASCADE)
    student_1=models.CharField(max_length=15)
    student_2=models.CharField(max_length=15)
    similarity_coeff=models.FloatField()

    def __str__(self):
        return self.student_1+' '+self.student_2+' '+str(self.similarity_coeff)

account/views.py
import csv
from github import Github
from html.parser import HTMLParser
from .keywords import html_close_map, html_open_map
from pprint import pprint
from typing_extensions import final

def home_page_unit(request):
    return render(request,'app/home1.html')
# Creds
TOKEN = "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"
g = Github(TOKEN)

class MyHTMLParser(HTMLParser):
    def __init__(self):
        HTMLParser.__init__(self)
        self.to_ret = {}
        self.token = ""
        self.content_data = []
        self.ids = []
        self.classes = []
        self.type = []
        self.value = []
        self.hrefs = []
        self.srcs = []
        self.others = []


    def handle_starttag(self, tag, attrs):
        if tag in html_open_map:
            self.token += html_open_map[tag]
        else:
            ## MEANS A TAG WHICH HAS NOT BEEN TAUGHT IS BEING USED ##
            self.token += "+"
        for attr in attrs:
            # print(attr[0], attr[1])
            if attr[0] == 'id':
                self.ids.append(attr[1])
            elif attr[0] == 'class':
                self.classes.append(attr[1])
            elif attr[0] == 'href':
                self.hrefs.append(attr[1])
            elif attr[0] == 'type':
                self.type.append(attr[1])
            elif attr[0] == 'src':
                self.srcs.append(attr[1])
            else:
                self.others.append(attr[1])


    def handle_endtag(self, tag):
        if tag in html_close_map:
            self.token += html_close_map[tag]
        else:
            ## MEANS A TAG WHICH HAS NOT BEEN TAUGHT IS BEING USED ##
            self.token += "="

    def handle_data(self, data):
        self.content_data.append(data)


    def get_token(self):
        self.to_ret['token'] = self.token
        self.to_ret['content_data'] = self.content_data
        self.to_ret['ids'] = self.ids
        self.to_ret['classes'] = self.classes
        self.to_ret['type'] = self.type
        self.to_ret['value'] = self.value
        self.to_ret['hrefs'] = self.hrefs 
        self.to_ret['srcs'] = self.srcs 
        self.to_ret['others'] = self.others 
        return self.to_ret
    

def list_similarity(list1, list2):

    try:
        res = len(set(list1) & set(list2)) / float(len(set(list1) | set(list2))) * 100
        return res
    except:
        return 0


def edit_distance(cozam1, cozam2):
    """
    classical lavenstein distance - edit distance algo 
    """

    s1 = cozam1
    s2 = cozam2
    n = len(s1)
    m = len(s2)
    dp = [[0 for i in range(n+1)]for j in range(m+1)]
    for i in range(n+1):
        dp[0][i] = i
    for i in range(m+1):
        dp[i][0] = i

    for i in range(1, m+1):
        for j in range(1, n+1):
            if s2[i-1] == s1[j-1]:
                dp[i][j] = dp[i-1][j-1]
            else:
                dp[i][j] = min(dp[i-1][j-1], dp[i-1][j], dp[i][j-1]) + 1
    ans = dp[m][n]
    return ans


def calculate_similarity_coeff(cozam_fst, cozam_sec):
    """
    Runs the standard min-edit distance algo and returns a % of similarity 
    between tokenised version of both codes
    """
    #print(cozam_fst, cozam_sec)
    len_fst = len(cozam_fst)
    len_sec = len(cozam_sec)
    min_ed = edit_distance(cozam_fst, cozam_sec)
    base = max(len_fst, len_sec)
    similarity_coeffecient = (float(base - min_ed)/float(base)) * 100
    return round(similarity_coeffecient, 2) 


def remove_css(code):
    """
    as the name describes, it removes the css part from html code
    """
    final_code = code
    if '<style>' in code:
        removal_start = code.find('<style>')
        removal_end = code.find('</style>') + len('</style>')
        final_code = code[:removal_start] + code[removal_end:] 
    return final_code


def get_code(file_name, extension, student1_repo):
    url = student1_repo
    repo = g.get_repo(url)
    print("how you doiin")
    print(repo)
    sub_url = file_name + extension
    try:
        contents = repo.get_contents(sub_url)
        s_code = contents.decoded_content.decode()
    except:
        pprint("Error here")
        return -1
    return s_code

## Just fill the list with student github file links, filename, extension and the work will be done 
#
STUDENTS_GITHUB = ["mahesh_fw14_576", "shoaib_fw14_157","tejaswini_fw14_688","megha_fw14_307","nikhil_fw14_698", "alok_fw14_018"]
#,“masai-course/tarasish_fw14_482”]FILENAME = "getPayment"
from .models import PlagiarismRecordU_2
from blog.models import PlagiarismReport
from blog.forms import ReportForm
from blog.views import get_particular_code
from blog.encryption_util import encrypt,decrypt
def get_report(request):
    form = ReportForm()
    print("before")
    if request.method == 'GET':
        form = ReportForm(request.GET)	
        context = {'form':form, 'unit': "unit-2"}
        return render(request, 'app/form_u2.html', {'form':form, 'unit': "unit-2"})
    form = ReportForm(request.POST)	
    token=form['token'].value()
    if len(token)!=0:
        decrepted=decrypt(token)
        #print("dec "+decrepted)
        decrept=decrepted.split('#')
        cohort=decrept[0]
        unit=decrept[1]
        sprint=decrept[2]
        filename=decrept[3]
        
        extension=decrept[4]
        print(cohort+" "+unit+" "+sprint+" "+filename+" "+extension)
    else:
    
        cohort=form['cohort_id'].value()
        unit=form['unit'].value()
        sprint=form['sprint'].value()
        filename=form['filename'].value()
        extension=form['extension'].value()
    s='SELECT id from blog_plagiarismreport where cohort_id="'+cohort+'" and unit='+str(unit)+' and sprint='+str(sprint)+' and filename="'+filename+'"and extension="'+extension+'"'
    id= PlagiarismReport.objects.raw(s)
    # print(id[0].id)
    try:
        x=id[0]
    except:
        return HttpResponse("no record found")
    
    s='select id,student_1,student_2,similarity_code,similarity_ids,similarity_classes,similarity_content,similarity_type,similarity_value,similatity_hrefs,similarity_others from account_PlagiarismRecordU_2 where report_id='+str(id[0].id)
    records=PlagiarismRecordU_2.objects.raw(s)
    #return HttpResponse(records)
    unit_slug = 'unit-' + str(unit) + '/'
    sprint_slug = 'sprint-' + str(sprint) + '/'
    sub_url = unit_slug + sprint_slug + 'evaluation/' + filename + '.' + extension
    
    return render(request,'app/all_list.html',{'records':records,'sub_url':sub_url})



def generate_report(request):
    form = ReportForm()
    print("before")
    if request.method == 'GET':
        form = ReportForm(request.GET)	
        # context = {'form':form}
        # return render(request, 'app/form_u2.html', context)
        return render(request, 'app/form_u2.html', {'form':form, 'unit':"unit-2"})
    form = ReportForm(request.POST)	
    print(form['unit'].value())
    cohort=form['cohort_id'].value()
    unit=form['unit'].value()
    sprint=form['sprint'].value()
    filename=form['filename'].value()
    extension=form['extension'].value()
    s='SELECT id from blog_plagiarismreport where cohort_id="'+form['cohort_id'].value()+'" and unit='+str(form['unit'].value())+' and sprint='+str(form['sprint'].value())+' and filename="'+form['filename'].value()+'"and extension="'+form['extension'].value()+'"'
    
    id= PlagiarismReport.objects.raw(s)
    
     #   s="YOur request is being processed try after 2 hours"
    try:
        x=id[0]
        key=cohort+"#"+unit+"#"+sprint+"#"+filename+"#"+extension
        encrytedKey=encrypt(key)
        return HttpResponse("Record already exist Use the following key to retrieve "+encrytedKey )
   
    except:
        
        print('emty')
        report=PlagiarismReport(cohort_id=cohort,unit=unit,sprint=sprint,filename=filename,extension=extension)
        report.save()
        s='SELECT id from blog_PlagiarismRecordU_3report where cohort_id="'+cohort+'" and unit='+str(unit)+' and sprint='+str(sprint)+' and filename="'+filename+'"and extension="'+extension+'"'
         
        id= PlagiarismReport.objects.raw(s)[0]
    for i in range(len(STUDENTS_GITHUB)):
        student_1 = STUDENTS_GITHUB[i]
        parser_1 = MyHTMLParser()
        #code_1 = get_code("/unit 5/assignment/reduxthunk/index", ".html", student_1)
        code_1 = get_particular_code(student_1, unit, sprint, filename, extension)
                
        if code_1 != -1:   
            html_code_1 = remove_css(code_1)
            parser_1.feed(html_code_1)
            ids_1 = parser_1.get_token()['ids']
            token_1 = parser_1.get_token()['token']
            classes_1 = parser_1.get_token()['classes']
            content_data_1 = parser_1.get_token()['content_data']
            type_1 = parser_1.get_token()['type']
            value_1 = parser_1.get_token()['value']
            hrefs_1 = parser_1.get_token()['hrefs']
            srcs_1 = parser_1.get_token()['srcs']
            others_1 = parser_1.get_token()['others']
            for j in range(i + 1, len(STUDENTS_GITHUB)):
                student_2 = STUDENTS_GITHUB[j]
                parser_2 = MyHTMLParser()
                code_2 = get_particular_code(student_2, unit, sprint, filename, extension)
                if code_2 != -1:
                    html_code_2 = remove_css(code_2)
                    parser_2.feed(html_code_2)
                    ids_2 = parser_2.get_token()['ids']
                    token_2 = parser_2.get_token()['token']
                    classes_2 = parser_2.get_token()['classes']
                    content_data_2 = parser_2.get_token()['content_data']
                    type_2 = parser_2.get_token()['type']
                    value_2 = parser_2.get_token()['value']
                    hrefs_2 = parser_2.get_token()['hrefs']
                    srcs_2 = parser_2.get_token()['srcs']
                    others_2 = parser_2.get_token()['others']
                    similarity_code = round(calculate_similarity_coeff(token_1, token_2))

account/templates/app/all_list.html
<br>
<h2>Plagiarism report</h2>
<h4>Submission path: {{sub_url}}</h4>

<table border="1" style="width:400px;font-size: 12px;" class="table table-condensed">
    <tr>
        
        <th style="font-size: 12px;">STUDENT-1</th>
        <th>STUDENT-2</th>
        <th>similarity_code</th>
        <th>similarity_ids</th>
        <th>similarity_classes</th>        
        <th>similarity_content</th>
        <th>similarity_type</th>        
        <th>similarity_value</th>        
        <th>similatity_hrefs</th>    
        <th>similarity_srcs</th>        
        <th>similarity_others</th>
    </tr>
   
    
    {% for i in records  %}
    <td> </td>
    <tr> <b>
        
        <td style="font-size: 12px;">{{ i.student_1 }}</td>
        
        <td>{{ i.student_2 }}</td></b>
        <td>{{ i.similarity_code }}</td>
        <td>{{ i.similarity_ids }}</td>
        <td>{{ i.similarity_classes }}</td>
        <td>{{ i.similarity_content }}</td>
        <td>{{ i.similarity_type }}</td>
        <td>{{ i.similarity_value }}</td>
        <td>{{ i.similatity_hrefs }}</td>
        <td>{{ i.similarity_srcs }}</td>
        <td>{{ i.similarity_others }}</td>
        
    </tr>
    
    {% endfor %}      

  </table><br>


  <br>
<br>

account/templates/app/base.html
<!DOCTYPE html>
<html>
    <head>
         <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        {% if title %}
            <title>Plagiarism detection</title>
        {% else %}
            <title> Plagiarism detection</title>
        {% endif %}
    </head>
<body>
    <div class="container">

<a href="{% url 'student-home' %}">HOME</a>
            {% block content %}{% endblock %}
        </div>

      <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
</body>
</html>

account/templates/app/form_u2.html
<head>
    <title>Form Unit-2</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>
  <body>
      <center>
<div class="container" style="width:1280px;font-size: 25px;">
<h1>Report Form (Unit-2)</h1>
<hr>

<form action="" method="post" >
	{% csrf_token %} 
   
    <div class="form-group">
        <label for="id_cohort_id">Cohort id:</label>  <br>
    
       
      <input type="text" name="cohort_id" maxlength="15" required id="id_cohort_id" placeholder="pd_demo or fw14">
      </div>
      <div class="form-group">
           <label for="id_unit">Unit:</label> <br>
       
       
      <input type="number" name="unit" required id="id_unit" placeholder="3">
      
      </div>
    

      <div class="form-group">
          <label for="id_sprint">Sprint:</label>     <br>
       
       
      <input type="number" name="sprint" required id="id_sprint" placeholder="3 or 4">  
      
      </div>
      
    

      <div class="form-group">
          <label for="id_filename">Filename:</label>      <br>
       
       
      <input type="text" name="filename" maxlength="255" required id="id_filename" placeholder="news, search, index">
      </div>

      <div class="form-group">
          <label for="id_extension">Extension:</label>      <br>
       
     
      <input type="text" name="extension" maxlength="10" required id="id_extension" placeholder="html">
      
      </div>
      <div class="form-group">
        <label for="id_token">Token:</label>      <br>
     
   
        <textarea name="token" maxlength="10000"  id="id_token" rows="8">

        </textarea>
      </div>
      
	  <button type="submit" class="btn btn-default" style="width:200px;font-size: 35px; ">Submit</button>
	
</form>
</div>

</center>

account/templates/app/home1.html
<!-- <a href="https://www.linkpicture.com/view.php?img=LPic6290e44266e00811519351"><img src="https://www.linkpicture.com/q/logo.svg" type="image"></a>

<p><b>Home page for plagiarism detection Project Unit-2</b></p>
<br>CODING
<br>
<br>
<ul>

<li><a href="{% url 'unit2rep' %}"> create req for new report</a></li>
<li><a href="{% url 'unit2rec' %}"> read report</a></li>
</div> -->

<!DOCTYPE html>
<html lang="en">
<head>
    <!--
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    -->
    <title>Plagiarism Detector</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="banner">
        <div class="navbar">
            <img src="../../static/css/logo_1.jpg" class="logo" height="60" width="170">
            <ul>
                <li><a href="../home">Home</a></li>
                <!-- <li><a href="../../../firstPage/templates/app/default1.html">Home</a></li> -->
                <li><a href="#">About</a></li>
                <li><a href="../unit2">Unit-2</a></li>
                <li><a href="../unit3">Unit-3</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </div>
        <!-- <div class="content">
            <h1>Plag Detect in Your File</h1>
            <p>You are at the right place:<br>just fill the required fields and we are good to go.....!</p>
        </div> -->
        <div class="content">
            <h2>Plag Detect in Your File (for unit-2)</h2>
            <div>
                <!-- <button type="button"><span></span><a href="{% url 'unit2rep' %}"> Generate Report</a></button>
                <button type="button"><span></span><a href="{% url 'unit2rec' %}"> Read Report</a></button> -->
                <button onclick="location.href='../unit2/report'" type="button"><span></span>Generate Report</button>
                <button onclick="location.href='../unit2/record'" type="button"><span></span>Read Report</button>
            </div>
        </div>
    </div>
</body>
</html>

account/templates/app/index.html
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>
  <body>
      <center>
<div class="container" style="width:1280px;font-size: 25px;">
<h1>Report Form</h1>
<hr>

<form action="" method="post" >
	{% csrf_token %} 
   
    <div class="form-group">
        <label for="id_cohort_id">Cohort id:</label>  <br>
    
       
      <input type="text" name="cohort_id" maxlength="15" required id="id_cohort_id">
      </div>
      <div class="form-group">
           <label for="id_unit">Unit:</label> <br>
       
       
      <input type="number" name="unit" required id="id_unit">
      
      </div>
    

      <div class="form-group">
          <label for="id_sprint">Sprint:</label>     <br>
       
       
      <input type="number" name="sprint" required id="id_sprint">  
      
      </div>
      
    

      <div class="form-group">
          <label for="id_filename">Filename:</label>      <br>
       
       
      <input type="text" name="filename" maxlength="255" required id="id_filename">
      </div>

      <div class="form-group">
          <label for="id_extension">Extension:</label>      <br>
       
     
      <input type="text" name="extension" maxlength="10" required id="id_extension">
      
      </div>
      
      
    
    
	  <button type="submit" class="btn btn-default" style="width:200px;font-size: 35px; ">Submit</button>
	
</form>
</div>

</center>